name: Auto-add new issues to required project

on:
  issues:
    types: [opened, reopened, transferred]

permissions:
  contents: read
  repository-projects: write

jobs:
  ensure-project-membership:
    uses: recoverag/.github/.github/workflows/ensure-issue-in-project.yml@main
    with:
      required_project: ${{ vars.REQUIRED_PROJECT }}
